cursor:
  style:
    shape: Block
  vi_mode_style:
    shape: Block
font:
  size: 7
  bold:
    family: FiraCode Nerd Font
    style: Regular
  italic:
    family: FiraCode Nerd Font
    style: Regular
  normal:
    family: FiraCode Nerd Font
    style: Regular
selection:
  save_to_clipboard: true
shell:
  args:
    - -l
    - -c
    - tmux attach || tmux
  program: /bin/bash
window:
  opacity: 0.9
  dimensions:
    columns: 155
    lines: 45
