font:
  size: 9
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Regular
window:
  opacity: 0.9
  dimensions:
    columns: 155
    lines: 45
selection:
  save_to_clipboard: true
shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux attach || tmux"
cursor:
  style:
    shape: Beam
  vi_mode_style:
    shape: Beam
