[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Regular"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[window]
opacity = 0.9

[window.dimensions]
columns = 155
lines = 45
