#!/bin/bash

rcs=(
  $HOME/.envrc
  $HOME/.functionrc
  $HOME/.aliasrc
  $HOME/.selfrc
)

for f in ${rcs[*]}; do 
  [[ -f "$f" ]] && source $f
done


if [[ -d $HOME/.profile.d ]]; then
  for f in $HOME/.profile.d/*; do 
    source $f
  done
fi

