#!/bin/zsh

# 自動補全忽略大小寫
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# enable edit-command-line with editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

if [[ -f $HOME/.profile ]]; then
  source $HOME/.profile
fi
