#!/bin/bash

if ! command -v fzf > /dev/null 2>&1; then
  exit 0
fi

# fzf 配置
# export FZF_CTRL_T_COMMAND=ls       # 按下 C-t 時需要執行並將結果傳遞給 fzf 的命令
export FZF_DEFAULT_OPTS='--border' # 默認選項
export FZF_COMPLETION_TRIGGER='**' # 觸發模糊補全的字符序列
# export FZF_COMPLETION_TRIGGER=1
eval "$(fzf --${SHELL##*/})"

# case $SHELL in
#   *zsh)
#     bindkey -M emacs '^E' fzf-file-widget
#     ;;
#   *bash)
#     bind -m emacs-standard -x '"\C-e": fzf-file-widget'
#     ;;
#   *)
#     echo "$0: unset fzf keybind, unknow shell type"
#     ;;
# esac
