#!/bin/bash

if ! command -v yazi >/dev/null 2>&1; then
  return 0
fi

function y() {
  local tmp="$(mktemp -t "yazi-cwd")"
  if [[ -d "$1" ]]; then
    command yazi --cwd-file="$tmp" "$1"
  else
    command yazi --cwd-file="$tmp"
  fi
  yazi --clear-cache >/dev/null 2>&1
  if [[ -f "$tmp" ]]; then
    local cwd="$(cat "$tmp")"
    rm -f "$tmp"
    if [[ -n "$cwd" && "$cwd" != "$PWD" ]]; then
      cd "$cwd"
    fi
  fi
}

case $SHELL in
*zsh)
  zle -N y
  bindkey '^Y' y
  ;;
*bash)
  bind -m emacs-standard -x '"\C-y": y'
  ;;
*)
  echo "$0: unset yazi keybind, unknow shell type"
  ;;
esac
