#!/bin/bash

export _ZO_DATA_DIR="$HOME/.local/share/zoxide"
export _ZO_FZF_OPTS="--height 40% --layout=reverse"
export _ZO_MAXAGE=5000
export _ZO_RESOLVE_SYMLINKS=1

eval "$(zoxide init --cmd cd ${SHELL##*/})"


