font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  size: 7
window:
  opacity: 0.9
  dimensions:
    columns: 120
    lines: 35
selection:
  save_to_clipboard: true
shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux attach || tmux"
