font:
  size: 14
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Regular
window:
  opacity: 0.7
  dimensions:
    columns: 175
    lines: 45
selection:
  save_to_clipboard: true
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
cursor:
  style:
    shape: Block
  vi_mode_style:
    shape: Block
