numbered_command = true
mouse_support = false
focus_on_create = true
use_trash = true
watch_files = true
xdg_open = false
xdg_open_fork = true
case_insensitive_ext = false
zoxide_update = true
custom_commands = []

[display]
mode = "default"
automatically_count_files = true
collapse_preview = false
column_ratio = [1, 4, 4]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = true
line_number_style = "none"
linemode = "size"

[display.sort]
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 52428800
preview_protocol = "halfblocks"
preview_script = "~/.config/joshuto/script/preview_file" # make sure it's marked as executable
preview_shown_hook_script = "~/.config/joshuto/script/on_preview_shown"
preview_removed_hook_script = "~/.config/joshuto/script/on_preview_removed"

[search]
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "sensitive"
regex_case_sensitivity = "sensitive"
fzf_case_sensitivity = "insensitive"

[tab]
home_page = "home"
