[default_view]
keymap = [
  { keys = ["q"],      commands = ["quit"] },
  { keys = ["escape"], commands = ["escape"] },
  { keys = ["ctrl+r"], commands = ["reload_dirlist"] },
  { keys = ["ctrl+h"], commands = ["toggle_hidden"] },

  # arrow keys
  { keys = ["arrow_up"],    commands = ["cursor_move_up"] },
  { keys = ["arrow_down"],  commands = ["cursor_move_down"] },
  { keys = ["arrow_left"],  commands = ["cd .."] },
  { keys = ["arrow_right"], commands = ["open"] },

  # vim-like keybindings
  { keys = ["j"],      commands = ["cursor_move_down"] },
  { keys = ["k"],      commands = ["cursor_move_up"] },
  { keys = ["h"],      commands = ["cd .."] },
  { keys = ["l"],      commands = ["open"] },
  { keys = ["o"],      commands = ["open_with"] },
  { keys = ["G"],      commands = ["cursor_move_end"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },

  # inner command
  { keys = [":"],      commands = [":"] },
  { keys = ["'"],      commands = [":shell "] },
  { keys = ["c", "d"], commands = [":cd "] },
  { keys = ["m", "f"], commands = [":touch "] },
  { keys = ["m", "k"], commands = [":mkdir "] },

  # copy and paste
  { keys = ["p", "p"], commands = ["paste_files"] },
  { keys = ["d", "d"], commands = ["cut_files"] },
  { keys = ["y", "y"], commands = ["copy_files"] },
  { keys = ["y", "n"], commands = ["copy_filename"] },
  { keys = ["y", "f"], commands = ["copy_filepath"] },
  { keys = ["y", "d"], commands = ["copy_dirpath"] },


  # delete
  { keys = ["delete"], commands = ["delete_files --noconfirm"] },
  { keys = ["d", "D"], commands = ["delete_files --noconfirm"] },

  # rename
  { keys = ["a"],      commands = ["rename_append"] },
  { keys = ["i"],      commands = ["rename_prepend"] },
  { keys = ["c", "w"], commands = ["bulk_rename"] },

  # select
  { keys = [" "],      commands = ["select --toggle=true"] },
  { keys = ["v"],      commands = ["select --all=true --toggle=true"] },
  { keys = ["V"],      commands = ["toggle_visual"] },

  # search
  { keys = ["n"],      commands = ["search_next"] },
  { keys = ["N"],      commands = ["search_prev"] },
  { keys = ["/"],      commands = ["search_fzf"] },
  { keys = ["ctrl+f"], commands = ["subdir_fzf"] },

  # sort
  { keys = ["s", "r"], commands = ["sort reverse"] },
  { keys = ["s", "l"], commands = ["sort lexical"] },
  { keys = ["s", "m"], commands = ["sort mtime"] },
  { keys = ["s", "n"], commands = ["sort natural"] },
  { keys = ["s", "s"], commands = ["sort size"] },
  { keys = ["s", "e"], commands = ["sort ext"] },

  # linkmode
  { keys = ["m", "s"], commands = ["linemode size"] },
  { keys = ["m", "m"], commands = ["linemode mtime"] },
  { keys = ["m", "M"], commands = ["linemode size | mtime"] },
  { keys = ["m", "u"], commands = ["linemode user"] },
  { keys = ["m", "U"], commands = ["linemode user | group"] },
  { keys = ["m", "p"], commands = ["linemode perm"] },

  # other
  { keys = ["="], commands = ["set_mode"] },

  # goto
  { keys = ["g", "h"], commands = ["cd ~"] },
  { keys = ["g", "m"], commands = ["cd /mnt"] },
  { keys = ["g", "o"], commands = ["cd /opt"] },
  { keys = ["g", "d"], commands = ["cd ~/download"] },
  { keys = ["g", "j"], commands = ["cd ~/.config/joshuto"] },

  { keys = ["?"],      commands = ["help"] },
]

[task_view]
keymap = [
  # arrow keys
  # { keys = ["arrow_up"],   commands = ["cursor_move_up"] },
  # { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  # { keys = ["home"],       commands = ["cursor_move_home"] },
  # { keys = ["end"],        commands = ["cursor_move_end"] },
  # { keys = ["j"],          commands = ["cursor_move_down"] },
  # { keys = ["k"],          commands = ["cursor_move_up"] },
  # { keys = ["g", "g"],     commands = ["cursor_move_home"] },
  # { keys = ["G"],          commands = ["cursor_move_end"] },
  # { keys = ["w"],          commands = ["show_tasks"] },
  # { keys = ["escape"],     commands = ["show_tasks"] },
]

[help_view]
keymap = [
  # arrow keys
  { keys = ["arrow_up"],   commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"],       commands = ["cursor_move_home"] },
  { keys = ["end"],        commands = ["cursor_move_end"] },

  # vim-like keybindings
  { keys = ["j"],      commands = ["cursor_move_down"] },
  { keys = ["k"],      commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"],      commands = ["cursor_move_end"] },
  { keys = ["w"],      commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]
