taskkill /im GCPService.exe /f
taskkill /im GCPHost.exe /f
taskkill /im gdpsvc.exe /f
taskkill /im GCCPService.exe /f
taskkill /im gsupservice.exe /f
taskkill /im GSCMessenger.exe /f
taskkill /im gdphost.exe /f
taskkill /im GSCMessageBox.exe /f
taskkill /im GSCMonitor.exe /f
taskkill /im GSCNotifier.exe /f
taskkill /im GSCRegistry.exe /f
taskkill /im GSCScript.exe /f
taskkill /im GSCSenseShield.exe /f
taskkill /im GSCServer.exe /f
taskkill /im GSCService.exe /f
taskkill /im gchsvc.exe /f
taskkill /im crash_generation.exe /f
taskkill /im bugreport.exe /f
taskkill /im gcmpopbox.exe /f
taskkill /im gdpfeedback.exe /f
taskkill /im gsspservice.exe /f
taskkill /im SyncWorker.exe /f
taskkill /im gupdatebox.exe /f
taskkill /im gdphost.exe /f
taskkill /im gchsvc.exe /f
taskkill /im gdpsvc.exe /f
taskkill /im gupdatebox.exe /f