#! /bin/bash

# 输出 ASCII CODE 对照表

cat << 'EOF'
| ASCII Code | Character | Description            |  ASCII Code | Character | Description           | 
|------------|-----------|------------------------|-------------|-----------|-----------------------| 
| 000  0x00  | NUL       | Null character         |  064  0x40  | @         | At symbol             |
| 001  0x01  | SOH       | Start of Heading       |  065  0x41  | A         | Uppercase A           |
| 002  0x02  | STX       | Start of Text          |  066  0x42  | B         | Uppercase B           |
| 003  0x03  | ETX       | End of Text            |  067  0x43  | C         | Uppercase C           |
| 004  0x04  | EOT       | End of Transmission    |  068  0x44  | D         | Uppercase D           |
| 005  0x05  | ENQ       | Enquiry                |  069  0x45  | E         | Uppercase E           |
| 006  0x06  | ACK       | Acknowledge            |  070  0x46  | F         | Uppercase F           |
| 007  0x07  | BEL       | Bell                   |  071  0x47  | G         | Uppercase G           |
| 008  0x08  | BS        | Backspace              |  072  0x48  | H         | Uppercase H           |
| 009  0x09  | TAB       | Horizontal Tab         |  073  0x49  | I         | Uppercase I           |
| 010  0x0a  | LF        | Line Feed (New Line)   |  074  0x4a  | J         | Uppercase J           |
| 011  0x0b  | VT        | Vertical Tab           |  075  0x4b  | K         | Uppercase K           |
| 012  0x0c  | FF        | Form Feed              |  076  0x4c  | L         | Uppercase L           |
| 013  0x0d  | CR        | Carriage Return        |  077  0x4d  | M         | Uppercase M           |
| 014  0x0e  | SO        | Shift Out              |  078  0x4e  | N         | Uppercase N           |
| 015  0x0f  | SI        | Shift In               |  079  0x4f  | O         | Uppercase O           |
| 016  0x10  | DLE       | Data Link Escape       |  080  0x50  | P         | Uppercase P           |
| 017  0x11  | DC1       | Device Control 1       |  081  0x51  | Q         | Uppercase Q           |
| 018  0x12  | DC2       | Device Control 2       |  082  0x52  | R         | Uppercase R           |
| 019  0x13  | DC3       | Device Control 3       |  083  0x53  | S         | Uppercase S           |
| 020  0x14  | DC4       | Device Control 4       |  084  0x54  | T         | Uppercase T           |
| 021  0x15  | NAK       | Negative Acknowledge   |  085  0x55  | U         | Uppercase U           |
| 022  0x16  | SYN       | Synchronous Idle       |  086  0x56  | V         | Uppercase V           |
| 023  0x17  | ETB       | End of Transmit Block  |  087  0x57  | W         | Uppercase W           |
| 024  0x18  | CAN       | Cancel                 |  088  0x58  | X         | Uppercase X           |
| 025  0x19  | EM        | End of Medium          |  089  0x59  | Y         | Uppercase Y           |
| 026  0x1a  | SUB       | Substitute             |  090  0x5a  | Z         | Uppercase Z           |
| 027  0x1b  | ESC       | Escape                 |  091  0x5b  | [         | Left square bracket   |
| 028  0x1c  | FS        | File Separator         |  092  0x5c  | \         | Backslash             |
| 029  0x1d  | GS        | Group Separator        |  093  0x5d  | ]         | Right square bracket  |
| 030  0x1e  | RS        | Record Separator       |  094  0x5e  | ^         | Caret                 |
| 031  0x1f  | US        | Unit Separator         |  095  0x5f  | _         | Underscore            |
| 032  0x20  | Space     | Space                  |  096  0x60  | `         | Grave accent          |
| 033  0x21  | !         | Exclamation mark       |  097  0x61  | a         | Lowercase a           |
| 034  0x22  | "         | Double quote           |  098  0x62  | b         | Lowercase b           |
| 035  0x23  | #         | Number                 |  099  0x63  | c         | Lowercase c           |
| 036  0x24  | $         | Dollar                 |  100  0x64  | d         | Lowercase d           |
| 037  0x25  | %         | Percent                |  101  0x65  | e         | Lowercase e           |
| 038  0x26  | &         | Ampersand              |  102  0x66  | f         | Lowercase f           |
| 039  0x27  | '         | Single quote           |  103  0x67  | g         | Lowercase g           |
| 040  0x28  | (         | Left parenthesis       |  104  0x68  | h         | Lowercase h           |
| 041  0x29  | )         | Right parenthesis      |  105  0x69  | i         | Lowercase i           |
| 042  0x2a  | *         | Asterisk               |  106  0x6a  | j         | Lowercase j           |
| 043  0x2b  | +         | Plus                   |  107  0x6b  | k         | Lowercase k           |
| 044  0x2c  | ,         | Comma                  |  108  0x6c  | l         | Lowercase l           |
| 045  0x2d  | -         | Hyphen                 |  109  0x6d  | m         | Lowercase m           |
| 046  0x2e  | .         | Period                 |  110  0x6e  | n         | Lowercase n           |
| 047  0x2f  | /         | Slash                  |  111  0x6f  | o         | Lowercase o           |
| 048  0x30  | 0         | Digit 0                |  112  0x70  | p         | Lowercase p           |
| 049  0x31  | 1         | Digit 1                |  113  0x71  | q         | Lowercase q           |
| 050  0x32  | 2         | Digit 2                |  114  0x72  | r         | Lowercase r           |
| 051  0x33  | 3         | Digit 3                |  115  0x73  | s         | Lowercase s           |
| 052  0x34  | 4         | Digit 4                |  116  0x74  | t         | Lowercase t           |
| 053  0x35  | 5         | Digit 5                |  117  0x75  | u         | Lowercase u           |
| 054  0x36  | 6         | Digit 6                |  118  0x76  | v         | Lowercase v           |
| 055  0x37  | 7         | Digit 7                |  119  0x77  | w         | Lowercase w           |
| 056  0x38  | 8         | Digit 8                |  120  0x78  | x         | Lowercase x           |
| 057  0x39  | 9         | Digit 9                |  121  0x79  | y         | Lowercase y           |
| 058  0x3a  | :         | Colon                  |  122  0x7a  | z         | Lowercase z           |
| 059  0x3b  | ;         | Semicolon              |  123  0x7b  | {         | Left curly bracket    |
| 060  0x3c  | <         | Less than              |  124  0x7c  | |         | Vertical bar          |
| 061  0x3d  | =         | Equals                 |  125  0x7d  | }         | Right curly bracket   |
| 062  0x3e  | >         | Greater than           |  126  0x7e  | ~         | Tilde                 |
| 063  0x3f  | ?         | Question mark          |  127  0x7f  | DEL       | Delete                |
EOF

