#! /bin/bash

for f in *; do
  # [ ! -f "$f" ] && continue
  snip="printf '$f' =~ s/(\(.+?\))|(\[.+?\])|({.+?})|(（.+?）)|\s*|Z-Library//gr;"
  nf=$(perl -e "$snip")
  if [ -e "$nf" ]; then 
    echo "skip: $f -> $nf"
    continue
  fi
  mv "$f" "$nf"
done
