#!/bin/bash

recoverf=$(mktemp)

# 功能: 支持對文件的一些列批量重命名功能
# 參數:
#   index: 使用序號爲文件重命名
#     -p: 文件名前綴
#     -P: 使用父目錄名作爲前綴
#     -i: 起始序號
#     -l: 序號長度, 不滿長度使用 0 填充
#     -d: 僅從命名目錄
#     -f: 僅從命名文件
#   bulk:  使用默認編輯器編輯當前文件列表並重命名
#     -f: 需要修改的文件列表, 默認當前目錄的所有文件
#   date:  按照文件創建日期重命名文件爲: YYYY-mm-dd_HHMMSS

# 功能: 將當前目錄下的所有文件（不包含隱藏文件）重命名爲“前綴+index” 的格式
# 參數:
#   -p: 文件名前綴，爲空時格式化之後的結果只有 index
#   -i: 起始序號，默認從 0 開始，且會按照目錄下文件數量自動在前方添加 0
#   -l: 序號長度
#   -d: 僅從命名目錄
#   -f: 僅從命名文件
#   -p: 文件名前綴
# 注意: 此函數不會修改文件的後綴名，但默認了文件的後綴只有一個 .，對於 .tar.gz 的文件會被認爲後綴是 .gz 而不是 .tar.gz
function with_index() {
  echo "argument: $* $(pwd)" >> ~/tmp/bname.log
  # 參數解析kkk
  index=0
  while getopts "p:i:l:fdP" opt; do
    case $opt in
      p)
        prefix="$OPTARG"
        ;;
      i)
        index=$OPTARG
        ;;
      l)
        len=$OPTARG
        ;;
      f)
        fo=1
        ;;
      d)
        do=1
        ;;
      P)
        prefix="$(basename $(pwd))-"
        ;;
      *)
        echo "unknow arg: $OPTARG"
        ;;
    esac
  done

  # 自適應序號長度
  if [[ -z $len ]]; then
    fcnt=$(( ($(ls | wc -l) + index)))
    len=${#fcnt}
  fi

  # 文件重命名
  for f in *; do
    if [[ -f "$f" && ! -z "$do" ]] || [[ -d "$f" && ! -z "$fo" ]]; then
      continue
    fi

    idx_str=$(printf "%0${len}d" $index)
    if [[ -f "$f" ]]; then
      surfix=${f##*.}
      nf="${prefix}${idx_str}.${surfix}"
    elif [[ -d "$f" ]]; then
      nf="${prefix}${idx_str}"
    fi
    echo  "${f} -> ${nf}"
    if [[ -f $nf ]]; then
      echo "skip: $f to $nf"
      continue
    fi
    echo "$f -> $nf" | tee -a $recoverf
    mv "${f}" "${nf}"
    index=$(( index + 1 ))
  done
}

# 功能: 批量重命名文件 but 手動檔
function with_bulk() {
  file_list=""

  while getopts "f:" opt; do
    case $opt in
      f) file_list=$OPTARG ;;
    esac
  done

  if [[ "$file_list" == "" ]]; then
    file_list=$(mktemp)
    ls > $file_list
  fi

  if [[ ! -s "$file_list" ]]; then
    echo "nothing to do"
    exit 0
  fi

  bak=$(mktemp)
  cp "$file_list" "$bak"

  $EDITOR $file_list

  i=0
  while read f; do 
    i=$((i+1))
    nf=$(sed -n ${i}p $file_list)
    if [ -e "$nf" ]; then
      continue
    fi
    if [[ -f $nf ]]; then
      echo "skip: $f to $nf"
      continue
    fi

    echo "$f -> $nf" | tee -a $recoverf
    mv "$f" "$nf"
  done < $bak
}


# 功能: 按照文件創建時間重命名文件
# 依賴: 
#   - mdls: 用於讀取文件元數據, 獲取文件創建時間
function with_date() {
  for f in *; do
    t=$( mdls -name kMDItemContentCreationDate  "$f" | awk '{gsub(":", "", $4); printf "%s-%s\n", $3, $4}' )
    sub=${f##*.}
    nf="$t.$sub"
    if [[ -f $nf ]]; then
      echo "skip $f to $nf"
      continue
    fi
    echo "$f -> $nf" | tee -a $recoverf
    mv "$f" "$nf"
  done
}

# 功能: 按照 $recoverf 中記錄的變化將文件從命名回原本的樣子
# 參數:
#   $1: $recoverf 文件名
function recover () {
  local rf="$1"
  if [[ ! -f $rf ]]; then
    echo "unset recover file"
    return 1
  fi
  cat $rf | while read line; do
    f=$(echo $line | awk -F' -> ' '{print $1}')
    nf=$(echo $line | awk -F' -> ' '{print $2}')
    echo "$nf -> $f" | tee -a $recoverf
    mv $nf $f 
  done
}

# main
case $1 in
  date)
    with_date ${@:2}
    ;;
  index)
    with_index ${@:2}
    ;;
  bulk)
    with_bulk ${@:2}
    ;;
  recover)
    recover ${@:2}
    ;;
  help)
    # echo -n $HELPER
    ;;
  *)
    cat <<EOF
功能: 一系列批量重命名方法
使用方法 bname <index|bulk|date> [flags] [args]
參數:
  index: 使用序號爲文件重命名
    -p: 文件名前綴
    -i: 起始序號
    -l: 序號長度, 不滿長度使用 0 填充
  bulk:  使用默認編輯器編輯當前文件列表並重命名
    -f: 需要修改的文件列表, 默認當前目錄的所有文件
  date:  按照文件創建日期重命名文件爲: YYYY-mm-dd_HHMMSS
  recover: 恢復文件原本的名稱
    $1 之前使用 bname 修改文件名時生成的記錄文件
EOF
    ;;
esac

echo $recoverf
