#!/bin/bash

function checkpath() {
  # 对 PATH 变量进行检查
  IFS=":" read -ra path <<< "$PATH"
  for dir in "${path[@]}"; do
    [[ "$dir" =~ ^\$.* ]] && continue
    if [ ! -d "$dir" ] && [ "$dir" != '$PATH' ]; then
      echo -e "bad ${dir}"
    else
      echo -e "ok  $dir"
    fi
  done
}

checkpath | sort

unset -f checkpath
