#!/bin/bash

# 对 PATH 变量进行检查
IFS=":" read -ra path <<< "$PATH"
for dir in "${path[@]}"; do
  [[ "$dir" =~ ^\$.* ]] && continue
  if [ ! -d "$dir" ] && [ "$dir" != '$PATH' ]; then
    echo -e "\033[1;95;33mbad ${dir}\033[0m"
  else
    echo -e "\033[1;97;32mok  $dir\033[0m"
  fi
done
