#!/bin/bash

# 功能: 自動清理回收站和部分緩存信息
# 備註: cosb 名稱來源於 macos 清理廢紙簍的快捷鍵: Command + Option + Shift + Backspace

# 如果该目录为空 size 依旧会是 4k，但是影响不是很大，所以不做特别修正
function linux_clean() {
  size=$(du -d 0 -h ~/.local/share/Trash | awk '{print $1}')
  rm -rf ~/.local/share/Trash/*
  if [[ $? -eq 0 ]]; then
    echo "reclaimed: $size"
  fi
}

# 功能: macOS 使用 dot_calen 清理 HOME 目錄下的 .DS_* 和 ._* 文件
function mac_clean() {
  [[ -d $HOME/.local/share/Trash ]] && rm -rf $HOME/.local/share/Trash
  find . -type f -name '.DS_Store' -delete

  for d in ~/*; do
    [[ -d "$d" ]] && dot_clean "$d"
  done
}

if [[ $(uname -s) == "Darwin" ]]; then
  mac_clean
else
  linux_clean
fi

# /Users/iewzii/.local/share/CMakeTools
# /Users/iewzii/.local/state/nvim
# /Users/iewzii/.local/state/yazi
# /Users/iewzii/.local/state/btop.log
# /Users/iewzii/.cache
# /Users/iewzii/.npm
# /Users/iewzii/.rustup
# /Users/iewzii/.terminfo
