#! /bin/bash

# 清空废纸篓 Command + Option + Shift + Backspace
# 如果该目录为空 size 依旧会是 4k，但是影响不是很大，所以不做特别修正
size=$(du -d 0 -h ~/.local/share/Trash | awk '{print $1}')
rm -rf ~/.local/share/Trash/*
if [[ $? -eq 0 ]]; then
  echo "reclaimed: $size"
fi
