#!/bin/bash

# de-duplicate
# 刪除重複文件

if [[ "$(uname -s)" == "Darwin" ]]; then
  uuid=$(uuidgen)
else
  uuid=$(cat /proc/sys/kernel/random/uuid)
fi

logf="dedup-${uuid}"

find . -type f -exec md5sum {} \; 2>/dev/null | tee $logf
idx=$(awk '{print $1}' $logf | sort | uniq -d)
for i in ${idx[@]}; do
  echo ""
  echo "$i :"
  awk -v u="$i" '$1 == u {$1="";print NR $0}' $logf
  read -p "saved(default the first): " no
  if [ -z $no ]; then
    no=$(awk -v u="$i" '$1 == u {$1="";print NR}' $logf | head -n 1)
  fi
  awk -v u="$i" -v no="$no" '$1 == u && NR != no {$1="";print i $0}' $logf | while read line; do
    echo "remove $line"
    rm "$line"
  done
done

# 有些重复文件可能分布在不同文件夹,删除之后会出现空文件夹
find . -empty -type d -delete

rm $logf

