#! /bin/bash

# 一個簡單的進度條
progress=$1
total_steps=$2
max_length=50
filled_length=$(( progress * max_length / total_steps ))
empty_length=$(( max_length - filled_length ))
filled_bar=$(printf "%0.s#" $(seq 1 $filled_length))
empty_bar=$(printf "%0.s-" $(seq 1 $empty_length))

printf "\r\033[0;40;32m[%s%s] %d%% (%d / %d)\033[0m" "$filled_bar" "$empty_bar" "$(( progress * 100 / total_steps ))" "$progress" "$total_steps"
