#!/bin/zsh

# 功能: 將當前目錄下的所有音頻文件轉化爲 mp3 格式(不會遞歸轉化)
# 依賴:
#   - ffmpeg: 用於音頻格式轉化的實際程序

if [[ $(uname -s) != "Darwin" ]]; then
  echo "This script is intended for macOS only."
  exit 1
fi

if ! command -v ffmpeg > /dev/null 2>&1; then
  echo "not fond ffmpeg command, is required, you can install with brew: brew install ffmpeg"
  exit 1
fi

while getopts "r" opt; do
  case $opt in
    r)
      recursion=1
      ;;
    *)
      echo "unknow flag: $opt"
      exit 1
      ;;
  esac
done

function conver_to_mp3() {
  # 優先轉化當前目錄中的音頻文件然後遞歸處理子目錄中的文件
  for f in "$1"/*; do
    if [[ ! -f "$f" ]]; then
      continue
    fi
    m=$(file -b -I "$f" | awk -F'/' '{print $1}')
    if [[ $m != "audio" ]]; then
      echo "skip $f, not audio file type ($m)"
      continue
    fi

    nn="${f%.*}.mp3"
    if [[ -f "$nn" ]]; then
      echo "skip $f, file existed"
      continue
    fi
    ffmpeg -i "$f" -ab 320k "$nn" > /dev/null 2>&1
    if [[ $? -ne 0 ]]; then
      echo -e "\033[31mfaile      $f\033[0m"
      continue
    fi
    echo "successful $f"
  done

  # 遞歸處理子目錄
  if [[ $recursion -ne 0 ]]; then
    for d in "$1"/*; do
      if [[ -d "$d" && ! -z $(ls -A "$d") ]]; then
        echo "$d"
        conver_to_mp3 "$d"
      fi
    done
  fi
}

conver_to_mp3 .
