#!/bin/bash

current_dir=$(dirname $(realpath $0))
source $current_dir/mod.sh

if [[ -z "$1" ]]; then
  err "usage: smnt <block-device>"
fi

if [[ ! -b $1 ]]; then
  err "$1 not block device"
fi

mount_point=$(lsblk -no MOUNTPOINT $1)
if [[ "$mount_point" == "" ]]; then
  err "$1 not mount"
fi

udisksctl unmount -b $1
if [[ $? -ne 0 ]]; then
  err "unmout error"
fi

link_dir="$HOME/${mount_point##*/}"
if [[ -L $link_dir && ! -e $link_dir ]]; then
  rm $link_dir
fi
