#!/bin/bash
# get random photo from unsplash and set as desktop background
#
# api document: https://unsplash.com/documentation#get-a-random-photo
#

readonly RANDOM_PHOTO_API='https://api.unsplash.com/photos/random?orientation=landscape&collections=11649432'
readonly HEADER="Authorization:$UNSPLASH_KEY"
readonly DOWNLOAD_DIR="$HOME/picture/unsplash"

err() {
  echo $@ >& 2 
}

if [[ -z $UNSPLASH_KEY ]]; then
  err "not set UNSPLASH_KEY"
  exit 1
fi

[[ ! -d $DOWNLOAD_DIR ]] && mkdir -p $DOWNLOAD_DIR

# get random photo
echo "get random photo..."
rand_img_json=$(curl -s -H "$HEADER" $RANDOM_PHOTO_API)
id=$(echo $rand_img_json | jq -r ".id")
if [[ -z $id || $id == "null" ]]; then
  err "get random error, response: $rand_img_json"
  exit 1
fi

# get photo info
trigger_url=$(echo $rand_img_json | jq -r ".links.download_location")
down_url=$(curl -s -H "$HEADER" $trigger_url | jq -r '.url')
suffix=$(echo ${down_url#*\?} | grep -oE '(^|&)fm=[^&]*' | cut -d = -f 2)
img_name="$DOWNLOAD_DIR/$id.$suffix"

# download phtot
curl -s -H "$HEADER" -o $img_name $down_url
echo "saved file to $img_name"
if [[ -z $XAUTHORITY || -z $DISPLAY ]]; then
  err "not work in X, just download file ($XAUTHORITY,$DISPLAY)" 
  exit 1
fi

feh --bg-fill $img_name

