#!/bin/bash
# get random photo from unsplash and set as desktop background
#
# api document: https://unsplash.com/documentation#get-a-random-photo
#

# set -ue

RANDOM_PHOTO_API='https://api.unsplash.com/photos/random?orientation=landscape&collections=11649432'
DOWNLOAD_DIR="$HOME/picture/unsplash"
DISPLAY=":0"
XAUTHORITY=$(find /tmp/ -name "xauth_*" 2>/dev/null || true)

[ ! -d $DOWNLOAD_DIR ] && mkdir -p $DOWNLOAD_DIR

echo "get random photo..."
rand_img_json=$(curl -s -H "Authorization:$UNSPLASH_KEY" $RANDOM_PHOTO_API)
id=$(echo $rand_img_json | jq -r ".id")

echo "track a photo download"
trigger_url=$(echo $rand_img_json | jq -r ".links.download_location")
down_url=$(curl -s -H "Authorization:$UNSPLASH_KEY" $trigger_url | jq -r '.url')
suffix=$(echo ${down_url#*\?} | grep -oE '(^|&)fm=[^&]*' | cut -d = -f 2)
img_name="$DOWNLOAD_DIR/$id.$suffix"

echo "download file to $img_name"
curl -s -H "Authorization:$UNSPLASH_KEY" -o $img_name $down_url
feh --bg-fill $img_name
