#!/bin/bash

# 移動長寬比小於 1 的圖片到單獨目錄

current_dir=$(dirname $(realpath $0))
source $current_dir/mod.sh

uuid=$(cat /proc/sys/kernel/random/uuid)

for f in *; do
  if [ ! -f "$f" ]; then
    continue
  fi

  mime=$(exiftool -MimeType "$f" | awk '{print $4}' | awk -F'/' '{print $1}')
  if [ "$mime" != "image" ]; then
    continue
  fi

  prate=$(echo $(magick "$f" -ping -format "scale=2; %w / %h" info:)|bc)
  if (( $(echo "$prate < 1" | bc -l) )); then
    [ ! -d "$uuid" ] && mkdir "$uuid"
    mv "$f" "$uuid/"
    echo $f
    continue
  fi
done
