#!/bin/bash

# 移動長寬比小於 1 的圖片到單獨目錄

# current_dir=$(dirname $(realpath $0))
# source $current_dir/mod.sh

if [[ $(uname -s) == "Darwin" ]]; then
  uuid=$(uuidgen)
else
  uuid=$(cat /proc/sys/kernel/random/uuid)
fi

for f in *; do
  echo "$f"
  if [ -d "$f" ]; then
    cd "$f"
    wide-img > /dev/null 2>&1 &
    cd ..
    continue
  fi
  if [ ! -f "$f" ]; then
    continue
  fi

  if [[ $(uname -s) == 'Darwin' ]]; then
    mime=$(file --mime-type "$f" | awk  '{print $2}' | awk -F'/' '{print $1}')
  else
    mime=$(exiftool -MimeType "$f" | awk '{print $4}' | awk -F'/' '{print $1}')
  fi
  if [ "$mime" != "image" ]; then
    continue
  fi

  prate=$(echo $(magick "$f" -ping -format "scale=2; %w / %h" info:)|bc)
  if (( $(echo "$prate < 1" | bc -l) )); then
    [ ! -d "$uuid" ] && mkdir "$uuid"
    mv "$f" "$uuid/"
    continue
  fi
done

wait

exit 0
