"基础配置
syntax on
set number relativenumber
set ruler
set wrap                      "自动折行
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab                  "将tab替换为相应数量空格
set smartindent
set backspace=2
set co=5

"设置取消备份 禁止临时文件
set nobackup
set noswapfile

"设置匹配模式 类似当输入一个左括号时会匹配相应的那个右括号
set showmatch
set clipboard^=unnamed,unnamedplus
set cursorline     "突出显示当前行
set fdm=marker