alias c='clear'
alias e='exit'
alias l='ls'
alias ll='ls -l'
alias vi=vim
alias sn='shutdown now'

export GTK_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export QT_IM_MODULE=fcitx5
export INPUT_METHOD=fcitx5