alias c='clear'
alias e='tmux suspend-client || exit'
# alias ls='ls --color=never'
alias l='ls'
alias la='ls -a'
alias ll='ls -lh'
alias lla='ls -alh'
alias lh='du --max-depth=1 -h --exclude="./.*"'
alias lah='du --max-depth=1 -h'
alias resource='source ~/.bashrc'
alias 7z=7zz
alias t='tmux attach || tmux'
alias rime='killall fcitx5 && fcitx5-remote -r'
alias baidu='curl https://www.baidu.com'
alias google='curl https://www.google.com'
